### PR TITLE
Add ability to search in translated text.

### PR DESCRIPTION
**Pull request by christopheNan**
This adds two new options (not avaliable in grep!): 
--right to search in translated text
--no-left to NOT search in original text

### CODE REVIEW

**Comment by JulienPalard** [comment]
`--right` and `--left` only make sense when you already ran the tool once. Would `--msgid` and `--msgstr` be better? I'm not sure as user of poedit won't see those strings either.

**Comment by christopheNan** [comment]
PoEdit users are familiar with "right" and "left" for translated and original text.
The *find* command in PoEdit uses "source texts" and "translations". (BTW it adds an option to search in comments).
So "--source" and "--translation" might be other candidates.

**Comment by JulienPalard** [comment]
@christopheNan This PR conflicts, can you fix it?

> So "--source" and "--translation" might be other candidates.

I think they make more sense than left and right.

**Comment by JulienPalard** [comment]
@christopheNan this still conflicts, could you rebase it on top of master?

**Comment by JulienPalard** [comment]
Thanks for this PR!

**Pull request merged**
